/* =====================================================================
   MSSQL(T-SQL) 레거시 단골 문법 모음 - 한 블록씩 드래그해서 실행해 보세요.
   접속: localhost,1433 / PLAYDB / play / Play!2345
   ===================================================================== */
USE PLAYDB;

-- 1. NULL 처리 : ISNULL(2개 인자) / COALESCE(여러 개)
SELECT EMP_NO, EMP_NM, ISNULL(EMAIL, '(없음)') AS EMAIL, COALESCE(SAL, 0) AS SAL FROM TB_EMP;

-- 2. 문자열 : + 연결, LEN, SUBSTRING, LEFT/RIGHT, REPLACE, CHARINDEX
SELECT EMP_NM + '(' + EMP_NO + ')'          AS NM_NO,
       LEN(EMP_NM)                          AS NM_LEN,
       LEFT(HIRE_DT, 4)                     AS HIRE_YEAR,
       SUBSTRING(EMAIL, 1, CHARINDEX('@', EMAIL) - 1) AS MAIL_ID
  FROM TB_EMP WHERE EMAIL IS NOT NULL;

-- 3. 날짜 : GETDATE, CONVERT 스타일 번호(112=yyyyMMdd, 120=yyyy-MM-dd HH:mi:ss, 23=yyyy-MM-dd), DATEADD, DATEDIFF
SELECT GETDATE()                              AS NOW_DT,
       CONVERT(VARCHAR(8), GETDATE(), 112)    AS YYYYMMDD,
       CONVERT(VARCHAR(19), GETDATE(), 120)   AS YMDHMS,
       FORMAT(GETDATE(), 'yyyy-MM-dd')        AS FORMATTED,      -- 2012+
       DATEADD(MONTH, -1, GETDATE())          AS ONE_MONTH_AGO;

SELECT EMP_NM, HIRE_DT,
       DATEDIFF(YEAR, CONVERT(DATE, HIRE_DT), GETDATE()) AS YEARS   -- 'YYYYMMDD' 문자열 → DATE
  FROM TB_EMP;

-- 4. 조건 : CASE / IIF(2012+)
SELECT EMP_NM, SAL,
       CASE WHEN SAL >= 90000000 THEN 'A' WHEN SAL >= 60000000 THEN 'B' ELSE 'C' END AS GRADE,
       IIF(USE_YN = 'Y', N'재직', N'퇴사') AS STATUS
  FROM TB_EMP;

-- 5. TOP / 페이징
SELECT TOP 5 * FROM TB_EMP ORDER BY SAL DESC;
SELECT * FROM TB_EMP ORDER BY EMP_NO OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;          -- 2012+
SELECT * FROM (SELECT ROW_NUMBER() OVER (ORDER BY EMP_NO) AS RN, * FROM TB_EMP) A
 WHERE RN BETWEEN 6 AND 10;                                                         -- 2005+ (레거시에 많음)

-- 6. 분석 함수
SELECT DEPT_CD, EMP_NM, SAL,
       RANK()      OVER (PARTITION BY DEPT_CD ORDER BY SAL DESC) AS RNK,
       SUM(SAL)    OVER (PARTITION BY DEPT_CD)                   AS DEPT_SUM
  FROM TB_EMP;

-- 7. 계층 조회 : 재귀 CTE
WITH T AS (
    SELECT 1 AS LVL, DEPT_CD, DEPT_NM, UP_DEPT_CD FROM TB_DEPT WHERE UP_DEPT_CD IS NULL
    UNION ALL
    SELECT T.LVL + 1, D.DEPT_CD, D.DEPT_NM, D.UP_DEPT_CD FROM TB_DEPT D JOIN T ON D.UP_DEPT_CD = T.DEPT_CD
)
SELECT REPLICATE('  ', LVL - 1) + DEPT_NM AS TREE, * FROM T;

-- 8. 문자열 집계 : STRING_AGG(2017+) / 레거시는 FOR XML PATH
SELECT DEPT_CD, STRING_AGG(EMP_NM, ', ') AS NAMES FROM TB_EMP GROUP BY DEPT_CD;
SELECT D.DEPT_CD,
       STUFF((SELECT ', ' + E.EMP_NM FROM TB_EMP E WHERE E.DEPT_CD = D.DEPT_CD FOR XML PATH('')), 1, 2, '') AS NAMES
  FROM TB_DEPT D;

-- 9. UPDATE ... FROM (JOIN 업데이트, MSSQL 전용 문법)
BEGIN TRAN;
UPDATE E SET E.SAL = E.SAL * 1.1
  FROM TB_EMP E JOIN TB_DEPT D ON D.DEPT_CD = E.DEPT_CD
 WHERE D.DEPT_NM = N'플랫폼팀';
SELECT EMP_NM, SAL FROM TB_EMP WHERE DEPT_CD = 'D210';
ROLLBACK;      -- 연습이니 되돌리기

-- 10. MERGE (있으면 UPDATE, 없으면 INSERT)
BEGIN TRAN;
MERGE TB_COMM_CODE AS T
USING (SELECT 'POS' AS GRP_CD, '60' AS CD, N'임원' AS CD_NM, 6 AS SORT_SEQ) AS S
   ON T.GRP_CD = S.GRP_CD AND T.CD = S.CD
 WHEN MATCHED THEN UPDATE SET T.CD_NM = S.CD_NM, T.SORT_SEQ = S.SORT_SEQ
 WHEN NOT MATCHED THEN INSERT (GRP_CD, CD, CD_NM, SORT_SEQ) VALUES (S.GRP_CD, S.CD, S.CD_NM, S.SORT_SEQ);
SELECT * FROM TB_COMM_CODE WHERE GRP_CD = 'POS';
ROLLBACK;

-- 11. 프로시저 실행 / 변수
DECLARE @NO VARCHAR(10);
EXEC dbo.USP_GET_NEXT_EMP_NO @NEXT_EMP_NO = @NO OUTPUT;
SELECT @NO AS NEXT_EMP_NO;
EXEC dbo.USP_DEPT_SAL_SUMMARY @USE_YN = 'Y';

-- 12. 임시 테이블 (#) - 레거시 프로시저에 매우 많음
SELECT DEPT_CD, COUNT(*) AS CNT INTO #DEPT_CNT FROM TB_EMP GROUP BY DEPT_CD;
SELECT * FROM #DEPT_CNT;
DROP TABLE #DEPT_CNT;

-- 13. 메타 정보 조회
EXEC sp_help 'TB_EMP';
EXEC sp_helptext 'USP_DEPT_SAL_SUMMARY';     -- 프로시저 소스 보기
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_EMP';
