-- =============================================================
-- Oracle: 테이블 / 시퀀스 / 프로시저  (MSSQL과 같은 구조)
--   비교 포인트: NVARCHAR→VARCHAR2, DECIMAL→NUMBER, DATETIME→DATE,
--               GETDATE()→SYSDATE, IDENTITY/MAX+1→SEQUENCE
-- =============================================================
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = PLAY;

CREATE TABLE TB_COMM_CODE (
    GRP_CD      VARCHAR2(20)   NOT NULL,
    CD          VARCHAR2(20)   NOT NULL,
    CD_NM       VARCHAR2(100)  NOT NULL,
    SORT_SEQ    NUMBER(5)      DEFAULT 0 NOT NULL,
    USE_YN      CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_COMM_CODE PRIMARY KEY (GRP_CD, CD)
);

CREATE TABLE TB_DEPT (
    DEPT_CD     VARCHAR2(10)   NOT NULL,
    DEPT_NM     VARCHAR2(100)  NOT NULL,
    UP_DEPT_CD  VARCHAR2(10),
    USE_YN      CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_DEPT PRIMARY KEY (DEPT_CD)
);

CREATE TABLE TB_EMP (
    EMP_NO      VARCHAR2(10)   NOT NULL,
    EMP_NM      VARCHAR2(50)   NOT NULL,
    DEPT_CD     VARCHAR2(10),
    POS_CD      VARCHAR2(10),
    HIRE_DT     CHAR(8),
    SAL         NUMBER(12),
    EMAIL       VARCHAR2(100),
    USE_YN      CHAR(1)        DEFAULT 'Y' NOT NULL,
    REG_ID      VARCHAR2(20),
    REG_DTM     DATE           DEFAULT SYSDATE NOT NULL,
    UPD_ID      VARCHAR2(20),
    UPD_DTM     DATE,
    CONSTRAINT PK_TB_EMP PRIMARY KEY (EMP_NO)
);

-- 사번 채번용 시퀀스 (Oracle 레거시의 정석)
CREATE SEQUENCE SEQ_EMP_NO START WITH 100 INCREMENT BY 1 NOCACHE;

-- 사번 채번 프로시저 (OUT 파라미터)
CREATE OR REPLACE PROCEDURE USP_GET_NEXT_EMP_NO (
    O_NEXT_EMP_NO OUT VARCHAR2
) AS
BEGIN
    SELECT 'E' || LPAD(SEQ_EMP_NO.NEXTVAL, 4, '0')
      INTO O_NEXT_EMP_NO
      FROM DUAL;
END;
/

-- 부서별 급여 집계 프로시저 (SYS_REFCURSOR로 결과셋 반환)
CREATE OR REPLACE PROCEDURE USP_DEPT_SAL_SUMMARY (
    I_USE_YN  IN  CHAR DEFAULT 'Y',
    O_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN O_CURSOR FOR
        SELECT D.DEPT_CD, D.DEPT_NM,
               COUNT(E.EMP_NO)      AS EMP_CNT,
               NVL(SUM(E.SAL), 0)   AS SAL_SUM,
               NVL(ROUND(AVG(E.SAL)), 0) AS SAL_AVG
          FROM TB_DEPT D
          LEFT JOIN TB_EMP E ON E.DEPT_CD = D.DEPT_CD AND E.USE_YN = I_USE_YN
         GROUP BY D.DEPT_CD, D.DEPT_NM
         ORDER BY D.DEPT_CD;
END;
/
